spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?characterEncoding=UTF-8&&useSSL=false&serverTimezone=GMT%2B8&useUnicode=true
    username: root
    password: mysqlroot

demo:
  controller-package: center.init.demo.controller